### ISSUE TITLE
Not working with complex structures

### ISSUE THREAD

**Issue by quasipedia** [Neozaru/fluent-plugin-lookup#1]
Not sure if it's me using the wrong syntax or if it is a bug, but I can't get the plugin to successfully substitute a "nested property".

My user case is this one:  I have a log structure in which an object `geoip` holds a number of keys: `geoip.country`, `geoip.city`, `geoip.region`, etc...  I am trying to substitute the codes in one of these fields with their complete human-friendly names, but it fails:

```
<match geoip.** >
  type lookup
  add_tag_prefix lookup.
  table_file /path/whatever/here/regions.csv
  field geoip.region
</match>
```

I tried also with: `field geoip['region']` or `field geoit[region]` but had no luck either.

However, if I save the region information in a "fist-level" field such for exmaple `region` and set the configuration file with `field region` the lookup succeeds (so I am sure my table, the tag matching, the path to the table file, etc are all correct).

**What is the correct syntax to substitute a property nested within an object then?**

**Comment by Neozaru** [comment]
Hello.

You are right : this plugin doesn't support nested field.
However, this could be an interesting feature.

**Comment by Neozaru** [comment]
Updated and pushed to gems as 0.0.2.
Feedback appreciated.

Note that you will need to call the plugin multiple times since it process one field path per usage. (one for region, one for country, one for city, etc...)

**Comment by quasipedia** [comment]
Wow @Neozaru !!

I'm impressed! :smile:  I left office with a problem, I came back with a new version of the package upgraded just for my pleasure!

Thank you, it works as expected!
